name: .NET Core

on:
  release:
    name: Release

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: where are we
        run: pwd
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name=ChatHero-$tag
          unset CI
          # Build everything
          dotnet publish ./Chat -c Release -o "$release_name"

          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "ChatHero-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
